"""Recreate migrations

Revision ID: 69b8226a5f90
Revises: a5e84d649a36
Create Date: 2025-04-08 19:42:15.203602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b8226a5f90'
down_revision: Union[str, None] = 'a5e84d649a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('hierarchy_level', sa.Integer(), nullable=False))
    op.add_column('roles', sa.Column('can_cross_departments', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'can_cross_departments')
    op.drop_column('roles', 'hierarchy_level')
    # ### end Alembic commands ###
