"""added leave request column

Revision ID: bd8d28926a77
Revises: 05968531340a
Create Date: 2025-04-16 07:22:47.181864

"""
from email.policy import default
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8d28926a77'
down_revision: Union[str, None] = '05968531340a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balance', sa.Column('leave_requested', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_balance', 'leave_requested')
    # ### end Alembic commands ###
